name: museum_skills_w28
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: PlayFair
    fonts:
    - asset: media-files/fonts/PlayfairDisplay-Regular.ttf
  - family: Optima
    fonts:
    - asset: media-files/fonts/Optima.ttc
  assets:
    - media-files/images/
    - media-files/images/michelangelo/
    - media-files/images/gustav_klimt/
    - media-files/images/leonardo_da_vinci/
    - media-files/data/artworks.json
